In [1]:
import numpy as np
import math

In [2]:
# Model 1
Prob1 = np.array([[0.4, 0.3, 0.3], [0.3, 0.4, 0.3], [0.5, 0.2, 0.3], [0.6, 0.2, 0.2]])
Ans1 = np.array([[1, 0, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1]])
print("Model 1")
print("Probability matrix :")
print(Prob1)
print("Answer matrix :")
print(Ans1)

# Model 2
Prob2 = np.array([[0.8, 0.1, 0.1], [0.1, 0.7, 0.2], [0.7, 0.1, 0.2], [0.4, 0.3, 0.3]])
Ans2 = np.array([[1, 0, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1]])
print("Model 2")
print("Probability matrix :")
print(Prob2)
print("Answer matrix :")
print(Ans2)

Model 1
Probability matrix :
[[0.4 0.3 0.3]
 [0.3 0.4 0.3]
 [0.5 0.2 0.3]
 [0.6 0.2 0.2]]
Answer matrix :
[[1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]]
Model 2
Probability matrix :
[[0.8 0.1 0.1]
 [0.1 0.7 0.2]
 [0.7 0.1 0.2]
 [0.4 0.3 0.3]]
Answer matrix :
[[1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]]


In [3]:
# calculate mean square error
se1 = np.power((Prob1 - Ans1), 2)
mse1 = np.mean(se1).sum()
se2 = np.power((Prob2 - Ans2), 2)
mse2 = np.mean(se2).sum()
print("MSE of Model 1:",mse1)
print("MSE of Model 2:",mse2)

MSE of Model 1: 0.20833333333333334
MSE of Model 2: 0.09000000000000001


In [4]:
# calculate mean absolute error
ae1 = abs(Prob1 - Ans1)
mae1 = np.mean(ae1).sum()
ae2 = abs(Prob2 - Ans2)
mae2 = np.mean(ae2).sum()
print("MAE of Model 1:",mae1)
print("MAE of Model 2:",mae2)

MAE of Model 1: 0.4166666666666666
MAE of Model 2: 0.25


In [5]:
# calculate cross entropy
ce1 = 0
ce2 = 0
for i in range(np.size(Prob1, 0)):
    for j in range(np.size(Prob1, 1)):
        a = Ans1[(i,j)]
        p = Prob1[(i,j)]
        ce1 -= (a * math.log(p) + (1 - a) * math.log(1 - p))
for i in range(np.size(Prob2, 0)):
    for j in range(np.size(Prob2, 1)):
        a = Ans2[(i,j)]
        p = Prob2[(i,j)]
        ce2 -= (a * math.log(p) + (1 - a) * math.log(1 - p))
ce1 /= np.size(Prob1)
ce2 /= np.size(Prob2)
print("MAE of Model 1:",ce1)
print("MAE of Model 2:",ce2)

MAE of Model 1: 0.6067599259115494
MAE of Model 2: 0.32297466470683817
