In [1]:
import numpy as np
import pandas as pd

In [2]:
# 圖像轉成矩陣(0為白色塊，1為黑色塊)
fig = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
         ,[0, 1, 1, 1, 1, 0, 0, 0, 1, 1]
         ,[0, 0, 1, 1, 1, 0, 1, 1, 1, 1]
         ,[0, 0, 1, 1, 0, 0, 1, 1, 1, 1]
         ,[0, 1, 1, 1, 0, 0, 1, 1, 1, 0]
         ,[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
         ,[0, 0, 0, 1, 1, 1, 0, 0, 1, 0]
         ,[0, 0, 0, 1, 1, 1, 1, 0, 0, 0]
         ,[0, 0, 0, 1, 1, 1, 1, 0, 0, 0]
         ,[0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])
print(fig)

# 讀取行列數
figrow = np.size(fig, 0)
figcol = np.size(fig, 1)
# 將原矩陣外圍加上一層零(預防程式計算出錯)
I1 = np.eye(figcol+2, figrow, k=-1)
I2 = np.eye(figcol, figrow+2, k=1)
fig2 = (I1.dot(fig)).dot(I2)
print(fig2)

# total 為全部 island 的總面積大小
total = sum(sum(fig))
print(total)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 1 1]
 [0 0 1 1 1 0 1 1 1 1]
 [0 0 1 1 0 0 1 1 1 1]
 [0 1 1 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 1 1 0 0 1 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
39


In [3]:
# 偵測元素(像素.pixel)上下左右是否有相連，判斷過後的值皆改為-1
def finding(fmatrix, i, j, count):
    if fmatrix[(i+1, j)] == 1:
        count += 1
        fmatrix[(i+1, j)] = -1
        fmatrix, count = finding(fmatrix, i+1, j, count)
    if fmatrix[(i, j+1)] == 1:
        count += 1
        fmatrix[(i, j+1)] = -1
        fmatrix, count = finding(fmatrix, i, j+1, count)        
    if fmatrix[(i-1, j)] == 1:
        count += 1
        fmatrix[(i-1, j)] = -1
        fmatrix, count = finding(fmatrix, i-1, j, count)
    if fmatrix[(i, j-1)] == 1:
        count += 1
        fmatrix[(i, j-1)] = -1
        fmatrix, count = finding(fmatrix, i, j-1, count)
        
    return fmatrix, count

In [4]:
island = []
x = 0
while total - sum(island) > 0:
    count = 0
    row = x // figcol + 1
    col = x % figcol + 1
    if fig2[(row, col)] == 1:
        count += 1
        # 判斷過後的值皆改為-1
        fig2[(row, col)] = -1
        fig2, count = finding(fig2, row, col, count)
        # 紀錄一個 island 的面積大小
        island.append(count)
    else:
        fig2[(row, col)] = -1
    x += 1

print(island)

[12, 15, 12]


In [5]:
# 整理 island 面積大小的資料
dic = {"Size of the area":island}
id = []
for i in range(len(island)):
    id.append("island " + str(i+1))
chart_result = pd.DataFrame(dic, index = id)
print("There are " + str(len(island)) + " islands in the figure.\n")
chart_result

There are 3 islands in the figure.



Size of the area
island 1                12
island 2                15
island 3                12